version: "3.8"

networks:
  koa_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

services:
  koa_server:
    restart: on-failure
    build:
      context: ../
      dockerfile: koa_server
    # build: . #当前文剑侠
    # image: koa_server:1.0.0
    networks:
      - koa_network
      # bridge:
        # ipv4_address: 172.25.0.3
    hostname: koa_server
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mysql_server
    environment:
      - DATABASE_DB=test
      - DATABASE_USER=root
      - DATABASE_PASSWORD=my-secret-root
      - DATABASE_HOST=mysql_server
      - NODE_ENV=development
      - DATABASE_PORT=3306
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:3000"]
      interval: 3s
      timeout: 600s
      retries: 30
      start_period: 40s
        
  mysql_server:
    image: mysql:5.7
    command: [
      '--default-authentication-plugin=mysql_native_password',
      # '--init-file',
      # '/docker-entrypoint-initdb.d/grant_permissions.sql'
    ]
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
    networks:
      - koa_network
      # bridge:
      #   ipv4_address: 172.25.0.2
    ports:
      - 3306:3306
    expose:
      - 3306

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:80
    depends_on:
      koa_server:
        condition: service_healthy
      # - koa_server1
      # - koa_server2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/log:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - koa_network
    expose:
      - 8080
    
volumes:
  mysql_data: {}
